/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Controle.Produto;
import dao.ProdutoDao;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alex
 */
public class Tabela_Produto_venda extends javax.swing.JDialog {
    
    private int referencia;
    private String modelo; 
    private String marca; 
    private int tamanho;
    private String cor;
    private double valor_venda;

    /**
     * Creates new form Tabela_Produto_venda
     */
    public Tabela_Produto_venda(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ListaAuto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabela_produto_vedas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tabela de Produtos");

        tabela_produto_vedas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Produto", "Referencia", "Modelo", "Marca", "Tamanho", "Quantidade", "Cor", "Valor Compra", "Valor Venda"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela_produto_vedas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tabela_produto_vedasKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tabela_produto_vedas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(918, 531));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public int getReferencia() {
        return referencia;
    }
    
    public String getModelo() {
        return modelo;
    }

    public String getMarca() {
        return marca;
    }

    public int getTamanho() {
        return tamanho;
    }

    public String getCor() {
        return cor;
    }

    public double getValor_venda() {
        return valor_venda;
    }
    
    

    private void tabela_produto_vedasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabela_produto_vedasKeyPressed
        
        int linha = tabela_produto_vedas.getSelectedRow();
        DefaultTableModel modelo = new DefaultTableModel();
        
        if (evt.getKeyCode()== KeyEvent.VK_ENTER){
        
            this.referencia = (int) tabela_produto_vedas.getModel().getValueAt(linha, 1);
            this.modelo = tabela_produto_vedas.getModel().getValueAt(linha, 2).toString();
            this.marca = tabela_produto_vedas.getModel().getValueAt(linha, 3).toString();
            this.tamanho = (int) tabela_produto_vedas.getModel().getValueAt(linha, 4);
            this.cor = tabela_produto_vedas.getModel().getValueAt(linha, 6).toString();
            this.valor_venda = (double) tabela_produto_vedas.getModel().getValueAt(linha, 8);
            this.dispose();
        
        }
        
    }//GEN-LAST:event_tabela_produto_vedasKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tabela_Produto_venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tabela_Produto_venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tabela_Produto_venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tabela_Produto_venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Tabela_Produto_venda dialog = new Tabela_Produto_venda(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    
    public void ListaAuto(){
    
        ProdutoDao ppd = new ProdutoDao();
        
        List <Produto> produto = ppd.listarProduto();
        DefaultTableModel modelo = new DefaultTableModel();
        
        modelo.addColumn("id_produto");
        modelo.addColumn("referencia");
        modelo.addColumn("modelo");
        modelo.addColumn("marca");
        modelo.addColumn("tamanho");
        modelo.addColumn("quantidade");
        modelo.addColumn("cor");
        modelo.addColumn("valor_compra");
        modelo.addColumn("valor_venda");
        
        Object rowData[] = new Object[9];
        for(int i=0; i<produto.size();i++){
            
            rowData[0] = produto.get(i).getId_produto();
            rowData[1] = produto.get(i).getReferencia();
            rowData[2] = produto.get(i).getModelo();
            rowData[3] = produto.get(i).getMarca();
            rowData[4] = produto.get(i).getTamanho();
            rowData[5] = produto.get(i).getQuantidade();
            rowData[6] = produto.get(i).getCor();
            rowData[7] = produto.get(i).getValor_compra();
            rowData[8] = produto.get(i).getValor_venda();
            
            modelo.addRow(rowData);
        }
        
        tabela_produto_vedas.setModel(modelo);
    
    
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela_produto_vedas;
    // End of variables declaration//GEN-END:variables
}
