/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Controle.Cliente;
import dao.ClienteDao;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alex
 */
public class Tabela_Cliente_Venda extends javax.swing.JDialog {
   Tela_venda venda;
   private String nome;
   private String cpf;
   private String telefone;
   private String email;
   private String rua;
   private String numero;
   private String bairro;
   private String cidade;
   private String estado;
   
    
    /**
     * Creates new form Tabela_Cliente_Venda
     */
    public Tabela_Cliente_Venda(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        listaAuto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabela_cliente_venda = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tabela de Clientes");

        tabela_cliente_venda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "CPF", "Telefone", "E-mail", "Rua", "Número", "Bairro", "Cidade", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela_cliente_venda.getTableHeader().setReorderingAllowed(false);
        tabela_cliente_venda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabela_cliente_vendaMouseClicked(evt);
            }
        });
        tabela_cliente_venda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tabela_cliente_vendaKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tabela_cliente_venda);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1038, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1056, 490));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void tabela_cliente_vendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabela_cliente_vendaMouseClicked
        
 
        
        
        
    }//GEN-LAST:event_tabela_cliente_vendaMouseClicked
        

    private void tabela_cliente_vendaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabela_cliente_vendaKeyPressed
        
       int linha = tabela_cliente_venda.getSelectedRow();
       DefaultTableModel modelo = new DefaultTableModel();
       
       if (evt.getKeyCode()== KeyEvent.VK_ENTER){
       
       this.nome = tabela_cliente_venda.getModel().getValueAt(linha, 0).toString();
       this.cpf = tabela_cliente_venda.getModel().getValueAt(linha, 1).toString();
       this.telefone = tabela_cliente_venda.getModel().getValueAt(linha, 2).toString();
       this.email = tabela_cliente_venda.getModel().getValueAt(linha, 3).toString();
       this.rua = tabela_cliente_venda.getModel().getValueAt(linha, 4).toString();
       this.numero = tabela_cliente_venda.getModel().getValueAt(linha, 5).toString();
       this.bairro = tabela_cliente_venda.getModel().getValueAt(linha, 6).toString();
       this.cidade = tabela_cliente_venda.getModel().getValueAt(linha, 7).toString();
       this.estado = tabela_cliente_venda.getModel().getValueAt(linha, 8).toString();
       this.dispose();
        
       /*
        
        if(venda == null){
        
           // venda = new Tela_venda();
           // venda.setVisible(true);
            venda.recebe(nome,cpf,telefone,email,rua,numero,bairro,cidade,estado);
            this.dispose();
            
        }else{     
            
           
          //  venda.setVisible(true);
            venda.setState(Tela_venda.NORMAL);
            venda.recebe(nome,cpf,telefone,email,rua,numero,bairro,cidade,estado);
            this.dispose();
        }
        */
          // System.err.println("teste");
       }
        
         
    }//GEN-LAST:event_tabela_cliente_vendaKeyPressed

    public String getNome() {
        return nome;
    }

    public String getCpf() {
        return cpf;
    }

    public String getTelefone() {
        return telefone;
    }

    public String getEmail() {
        return email;
    }

    public String getRua() {
        return rua;
    }

    public String getNumero() {
        return numero;
    }

    public String getBairro() {
        return bairro;
    }

    public String getCidade() {
        return cidade;
    }

    public String getEstado() {
        return estado;
    }

   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tabela_Cliente_Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tabela_Cliente_Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tabela_Cliente_Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tabela_Cliente_Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Tabela_Cliente_Venda dialog = new Tabela_Cliente_Venda(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela_cliente_venda;
    // End of variables declaration//GEN-END:variables

     public void listaAuto(){
    
         ClienteDao cd = new ClienteDao();
        
        List<Cliente> clientes = cd.listarClientes();
        
        DefaultTableModel modelo = new DefaultTableModel();
        
        //referenciando as tabelas do DB, entre "", com as colunas da tabela, na ordem definida na tabela desta tela.
        
       // modelo.addColumn("id_cliente");
        modelo.addColumn("nome");
        modelo.addColumn("cpf");
        modelo.addColumn("telefone");
        modelo.addColumn("email");
        modelo.addColumn("rua");
        modelo.addColumn("numero");
        modelo.addColumn("bairro");
        modelo.addColumn("cidade");
        modelo.addColumn("estado");
        
        Object rowData[] = new Object[9];
        
        System.out.println("Pesquisando clientes...");
        
        for(int i=0; i<clientes.size();i++){
            
           // rowData[0] = clientes.get(i).getId_cliente();
            rowData[0] = clientes.get(i).getNome();
            rowData[1] = clientes.get(i).getCpf();
            rowData[2] = clientes.get(i).getTelefone();
            rowData[3] = clientes.get(i).getEmail();
            rowData[4] = clientes.get(i).getRua();
            rowData[5] = clientes.get(i).getNumero();
            rowData[6] = clientes.get(i).getBairro();
            rowData[7] = clientes.get(i).getCidade();
            rowData[8] = clientes.get(i).getEstado();
            
            modelo.addRow(rowData); 
        }
        //tabelaCliente é o nome da tabela na tela Tela_cliente.
        tabela_cliente_venda.setModel(modelo);
    }
     
   

  
}
