/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Controle.Usuario;
import dao.UsuarioDao;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alex
 */
public class Tabela_Usuario_Venda extends javax.swing.JDialog {
    
    private String nome;

    /**
     * Creates new form Tabela_Usuario_Vendas
     */
    public Tabela_Usuario_Venda(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ListaAuto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabela_usuario_vedas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tabela de Fucionarios");

        tabela_usuario_vedas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id_Fucionario", "Nome", "Login", "CPF", "Telefone", "E-mail", "Rua", "Numero", "Bairro", "Cidade", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela_usuario_vedas.getTableHeader().setReorderingAllowed(false);
        tabela_usuario_vedas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tabela_usuario_vedasKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tabela_usuario_vedas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 818, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(836, 508));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public String getNome() {
        return nome;
    }
    
    private void tabela_usuario_vedasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabela_usuario_vedasKeyPressed
        
        int linha = tabela_usuario_vedas.getSelectedRow();
        DefaultTableModel modelo = new DefaultTableModel();
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
        this.nome = tabela_usuario_vedas.getModel().getValueAt(linha, 1).toString();
        this.dispose();
            
        }
        
    }//GEN-LAST:event_tabela_usuario_vedasKeyPressed
      
    public void ListaAuto(){
        
        UsuarioDao ud = new UsuarioDao();
    
        List<Usuario> usuarios = ud.listarUsuario();
        
        DefaultTableModel modelo = new DefaultTableModel();
        
        modelo.addColumn("id_usuario");
        modelo.addColumn("nome");
        modelo.addColumn("login");
        modelo.addColumn("senha");
        modelo.addColumn("cpf");
        modelo.addColumn("telefone");
        modelo.addColumn("email");
        modelo.addColumn("rua");
        modelo.addColumn("numero");
        modelo.addColumn("bairro");
        modelo.addColumn("cidade");
        modelo.addColumn("estado");
        
        Object rowData[] = new Object [12];
        
        for(int i = 0; i<usuarios.size(); i++){
            
            
            rowData[0] = usuarios.get(i).getId_usuario();
            rowData[1] = usuarios.get(i).getNome();
            rowData[2] = usuarios.get(i).getLogin();
            rowData[3] = usuarios.get(i).getSenha();
            rowData[4] = usuarios.get(i).getCpf();
            rowData[5] = usuarios.get(i).getTelefone();
            rowData[6] = usuarios.get(i).getEmail();
            rowData[7] = usuarios.get(i).getRua();
            rowData[8] = usuarios.get(i).getNumero();
            rowData[9] = usuarios.get(i).getBairro();
            rowData[10] = usuarios.get(i).getCidade();
            rowData[11] = usuarios.get(i).getEstado();
         
            modelo.addRow(rowData);
        }
        
        tabela_usuario_vedas.setModel(modelo);
        
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tabela_Usuario_Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tabela_Usuario_Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tabela_Usuario_Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tabela_Usuario_Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Tabela_Usuario_Venda dialog = new Tabela_Usuario_Venda(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela_usuario_vedas;
    // End of variables declaration//GEN-END:variables
}
