/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;


import Controle.Usuario;
import dao.UsuarioDao;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Israel
 */
public class Tela_usuario extends javax.swing.JFrame {

    /**
     * Creates new form Tela_produto
     */
    public Tela_usuario() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField_nome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField_cpf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField_telefone = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField_email = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField_rua = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField_numero = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField_bairro = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField_cidade = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField_estado = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField_login = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPasswordField_senha = new javax.swing.JPasswordField();
        jTextField1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton_salvar = new javax.swing.JButton();
        jButton_editar = new javax.swing.JButton();
        jButton_excluir = new javax.swing.JButton();
        btnLocalizar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1_usuario = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Usuario");

        jLabel1.setText("Nome:");

        jTextField_nome.setBackground(new java.awt.Color(255, 255, 204));

        jLabel2.setText("CPF:");

        jTextField_cpf.setBackground(new java.awt.Color(255, 255, 204));

        jLabel3.setText("Telefone:");

        jTextField_telefone.setBackground(new java.awt.Color(255, 255, 204));

        jLabel4.setText("E-mail:");

        jLabel5.setText("Rua:");

        jTextField_rua.setBackground(new java.awt.Color(255, 255, 204));

        jLabel6.setText("Num:");

        jTextField_numero.setBackground(new java.awt.Color(255, 255, 204));

        jLabel7.setText("Bairro:");

        jTextField_bairro.setBackground(new java.awt.Color(255, 255, 204));

        jLabel8.setText("Cidade:");

        jTextField_cidade.setBackground(new java.awt.Color(255, 255, 204));

        jLabel9.setText("Estado:");

        jTextField_estado.setBackground(new java.awt.Color(255, 255, 204));

        jLabel10.setText("Login:");

        jTextField_login.setBackground(new java.awt.Color(255, 255, 204));

        jLabel11.setText("Senha:");

        jPasswordField_senha.setBackground(new java.awt.Color(255, 255, 204));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(255, 255, 204));

        jLabel12.setText("Campos obrigatorios");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField_login, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPasswordField_senha))
                            .addComponent(jTextField_email)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField_bairro, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_estado))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField_rua, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_numero, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jPasswordField_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jTextField_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jTextField_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField_rua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField_numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField_bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton_salvar.setText("Salvar");
        jButton_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_salvarActionPerformed(evt);
            }
        });

        jButton_editar.setText("Editar");
        jButton_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_editarActionPerformed(evt);
            }
        });

        jButton_excluir.setText("Excluir");
        jButton_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_excluirActionPerformed(evt);
            }
        });

        btnLocalizar.setText("Localizar");
        btnLocalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocalizarActionPerformed(evt);
            }
        });

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(btnLocalizar)
                .addGap(54, 54, 54)
                .addComponent(jButton_editar)
                .addGap(70, 70, 70)
                .addComponent(jButton_excluir)
                .addGap(63, 63, 63)
                .addComponent(jButton_salvar)
                .addGap(71, 71, 71)
                .addComponent(btnSair)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_editar)
                    .addComponent(jButton_excluir)
                    .addComponent(btnLocalizar)
                    .addComponent(btnSair)
                    .addComponent(jButton_salvar))
                .addGap(39, 39, 39))
        );

        jTable1_usuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Login", "CPF", "Telefone", "E-mail", "Rua", "Número", "Bairro", "Cidade", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1_usuario.getTableHeader().setReorderingAllowed(false);
        jTable1_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1_usuarioMouseClicked(evt);
            }
        });
        jTable1_usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1_usuarioKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1_usuario);
        if (jTable1_usuario.getColumnModel().getColumnCount() > 0) {
            jTable1_usuario.getColumnModel().getColumn(0).setResizable(false);
        }

        jMenu1.setText("Arquivo");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Sair");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setSize(new java.awt.Dimension(839, 767));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        
            Principal tela_princi = new Principal();
            tela_princi.setExtendedState(Principal.MAXIMIZED_BOTH);
            tela_princi.setVisible(true);
            dispose();
        
    }//GEN-LAST:event_btnSairActionPerformed

    public void LimparCampos(){
    
    jTextField_nome.setText("");
    jTextField_login.setText("");
    jPasswordField_senha.setText("");
    jTextField_cpf.setText("");
    jTextField_telefone.setText("");
    jTextField_email.setText("");
    jTextField_rua.setText("");
    jTextField_numero.setText("");
    jTextField_bairro.setText("");
    jTextField_cidade.setText("");
    jTextField_estado.setText("");
    jTextField_nome.requestFocus();
    
    }
    
    private void jButton_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_salvarActionPerformed
       
        
            Usuario novoUsu = new Usuario();
                
                novoUsu.setNome(jTextField_nome.getText());
                novoUsu.setLogin(jTextField_login.getText());
                novoUsu.setSenha(jPasswordField_senha.getText());
                novoUsu.setCpf(jTextField_cpf.getText());
                novoUsu.setTelefone(jTextField_telefone.getText());
                novoUsu.setEmail(jTextField_email.getText());
                novoUsu.setRua(jTextField_rua.getText());
                novoUsu.setNumero(jTextField_numero.getText());
                novoUsu.setBairro(jTextField_bairro.getText());
                novoUsu.setCidade(jTextField_cidade.getText());
                novoUsu.setEstado(jTextField_estado.getText());
                
                UsuarioDao ud = new UsuarioDao();
                
                boolean v = ud.campoEmBranco(novoUsu);
                
                if(v == true){
                ud.salvar(novoUsu);
                JOptionPane.showMessageDialog(null, "Usuario cadastrado com sucesso!");
                }
                else
                {
                     JOptionPane.showMessageDialog(null, "Erro ao salvar!");
                }
                
                LimparCampos();
                
                List<Usuario> usuarios = ud.listarUsuario();
        
        DefaultTableModel modelo = new DefaultTableModel();
        
        modelo.addColumn("id_usuario");
        modelo.addColumn("nome");
        modelo.addColumn("login");
        modelo.addColumn("senha");
        modelo.addColumn("cpf");
        modelo.addColumn("telefone");
        modelo.addColumn("email");
        modelo.addColumn("rua");
        modelo.addColumn("numero");
        modelo.addColumn("bairro");
        modelo.addColumn("cidade");
        modelo.addColumn("estado");
        
        Object rowData[] = new Object [12];
        
        for(int i = 0; i<usuarios.size(); i++){
            
            
            rowData[0] = usuarios.get(i).getId_usuario();
            rowData[1] = usuarios.get(i).getNome();
            rowData[2] = usuarios.get(i).getLogin();
            rowData[3] = usuarios.get(i).getSenha();
            rowData[4] = usuarios.get(i).getCpf();
            rowData[5] = usuarios.get(i).getTelefone();
            rowData[6] = usuarios.get(i).getEmail();
            rowData[7] = usuarios.get(i).getRua();
            rowData[8] = usuarios.get(i).getNumero();
            rowData[9] = usuarios.get(i).getBairro();
            rowData[10] = usuarios.get(i).getCidade();
            rowData[11] = usuarios.get(i).getEstado();
         
            modelo.addRow(rowData);
        }
        
        jTable1_usuario.setModel(modelo);
        
                
    }//GEN-LAST:event_jButton_salvarActionPerformed
//String novo;
    private void jButton_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_excluirActionPerformed
        
        int linha = jTable1_usuario.getSelectedRow();
        
        if(linha < 0){
            JOptionPane.showMessageDialog(null, "Selecione um usuario para poder excluí-lo!");
        }
        
        String id = jTable1_usuario.getModel().getValueAt(linha, 0).toString();
        
        UsuarioDao ud = new UsuarioDao();
        
        if(ud.excluir(id) == true){
            ud.excluir(id);
            JOptionPane.showMessageDialog(null, "usuario portador do ID " + id + " excluído com sucesso!");
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Erro ao tentar excluir usuario portador do ID " + id + " !");
        }   
        
                 List<Usuario> usuarios = ud.listarUsuario();
        
        DefaultTableModel modelo = new DefaultTableModel();
        
        modelo.addColumn("id_usuario");
        modelo.addColumn("nome");
        modelo.addColumn("login");
        modelo.addColumn("senha");
        modelo.addColumn("cpf");
        modelo.addColumn("telefone");
        modelo.addColumn("email");
        modelo.addColumn("rua");
        modelo.addColumn("numero");
        modelo.addColumn("bairro");
        modelo.addColumn("cidade");
        modelo.addColumn("estado");
        
        Object rowData[] = new Object [12];
        
        for(int i = 0; i<usuarios.size(); i++){
            
            
            rowData[0] = usuarios.get(i).getId_usuario();
            rowData[1] = usuarios.get(i).getNome();
            rowData[2] = usuarios.get(i).getLogin();
            rowData[3] = usuarios.get(i).getSenha();
            rowData[4] = usuarios.get(i).getCpf();
            rowData[5] = usuarios.get(i).getTelefone();
            rowData[6] = usuarios.get(i).getEmail();
            rowData[7] = usuarios.get(i).getRua();
            rowData[8] = usuarios.get(i).getNumero();
            rowData[9] = usuarios.get(i).getBairro();
            rowData[10] = usuarios.get(i).getCidade();
            rowData[11] = usuarios.get(i).getEstado();
         
            modelo.addRow(rowData);
        }
        
        jTable1_usuario.setModel(modelo);
        
    }//GEN-LAST:event_jButton_excluirActionPerformed

    private void btnLocalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocalizarActionPerformed
       
        UsuarioDao ud = new UsuarioDao();
        
        List<Usuario> usuarios = ud.listarUsuario();
        
        DefaultTableModel modelo = new DefaultTableModel();
        
        modelo.addColumn("id_usuario");
        modelo.addColumn("nome");
        modelo.addColumn("login");
        modelo.addColumn("senha");
        modelo.addColumn("cpf");
        modelo.addColumn("telefone");
        modelo.addColumn("email");
        modelo.addColumn("rua");
        modelo.addColumn("numero");
        modelo.addColumn("bairro");
        modelo.addColumn("cidade");
        modelo.addColumn("estado");
        
        Object rowData[] = new Object [12];
        
        for(int i = 0; i<usuarios.size(); i++){
            
            
            rowData[0] = usuarios.get(i).getId_usuario();
            rowData[1] = usuarios.get(i).getNome();
            rowData[2] = usuarios.get(i).getLogin();
            rowData[3] = usuarios.get(i).getSenha();
            rowData[4] = usuarios.get(i).getCpf();
            rowData[5] = usuarios.get(i).getTelefone();
            rowData[6] = usuarios.get(i).getEmail();
            rowData[7] = usuarios.get(i).getRua();
            rowData[8] = usuarios.get(i).getNumero();
            rowData[9] = usuarios.get(i).getBairro();
            rowData[10] = usuarios.get(i).getCidade();
            rowData[11] = usuarios.get(i).getEstado();
         
            modelo.addRow(rowData);
        }
        
        jTable1_usuario.setModel(modelo);
        
    }//GEN-LAST:event_btnLocalizarActionPerformed

    private void jTable1_usuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1_usuarioMouseClicked

        
        int linha = jTable1_usuario.getSelectedRow();
        String id = jTable1_usuario.getModel().getValueAt(linha, 0).toString();
        String nome = jTable1_usuario.getModel().getValueAt(linha, 1).toString();
        String login = jTable1_usuario.getModel().getValueAt(linha, 2).toString();
        String senha = jTable1_usuario.getModel().getValueAt(linha, 3).toString();
        String cpf = jTable1_usuario.getModel().getValueAt(linha, 4).toString();
        String telefone = jTable1_usuario.getModel().getValueAt(linha, 5).toString();
        String email = jTable1_usuario.getModel().getValueAt(linha, 6).toString();
        String rua = jTable1_usuario.getModel().getValueAt(linha, 7).toString();
        String numero = jTable1_usuario.getModel().getValueAt(linha, 8).toString();
        String bairro = jTable1_usuario.getModel().getValueAt(linha, 9).toString();
        String cidade = jTable1_usuario.getModel().getValueAt(linha, 10).toString();
        String estado = jTable1_usuario.getModel().getValueAt(linha, 11).toString();
        
        jTextField_nome.setText(nome);
        jTextField_login.setText(login);
        jPasswordField_senha.setText(senha);
        jTextField_cpf.setText(cpf);
        jTextField_telefone.setText(telefone);
        jTextField_email.setText(email);
        jTextField_rua.setText(rua);
        jTextField_numero.setText(numero);
        jTextField_bairro.setText(bairro);
        jTextField_cidade.setText(cidade);
        jTextField_estado.setText(estado);
        
    }//GEN-LAST:event_jTable1_usuarioMouseClicked

    private void jButton_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_editarActionPerformed
 
        
        int linha = jTable1_usuario.getSelectedRow();
        
        if (linha < 0){
            JOptionPane.showMessageDialog(null, "Selecione um cliente para poder excluí-lo!");
        }
        
        String id = jTable1_usuario.getModel().getValueAt(linha,0).toString();
        
        Usuario novoUsu = new Usuario();
        
                novoUsu.setNome(jTextField_nome.getText());
                novoUsu.setLogin(jTextField_login.getText());
                novoUsu.setSenha(jPasswordField_senha.getText());
                novoUsu.setCpf(jTextField_cpf.getText());
                novoUsu.setTelefone(jTextField_telefone.getText());
                novoUsu.setEmail(jTextField_email.getText());
                novoUsu.setRua(jTextField_rua.getText());
                novoUsu.setNumero(jTextField_numero.getText());
                novoUsu.setBairro(jTextField_bairro.getText());
                novoUsu.setCidade(jTextField_cidade.getText());
                novoUsu.setEstado(jTextField_estado.getText());
                novoUsu.setId_usuario(Integer.parseInt(id));
                
                UsuarioDao ud = new UsuarioDao();
                ud.editar(novoUsu);
        
              List<Usuario> usuarios = ud.listarUsuario();
        
        DefaultTableModel modelo = new DefaultTableModel();
        
        modelo.addColumn("id_usuario");
        modelo.addColumn("nome");
        modelo.addColumn("login");
        modelo.addColumn("senha");
        modelo.addColumn("cpf");
        modelo.addColumn("telefone");
        modelo.addColumn("email");
        modelo.addColumn("rua");
        modelo.addColumn("numero");
        modelo.addColumn("bairro");
        modelo.addColumn("cidade");
        modelo.addColumn("estado");
        
        Object rowData[] = new Object [12];
        
        for(int i = 0; i<usuarios.size(); i++){
            
            
            rowData[0] = usuarios.get(i).getId_usuario();
            rowData[1] = usuarios.get(i).getNome();
            rowData[2] = usuarios.get(i).getLogin();
            rowData[3] = usuarios.get(i).getSenha();
            rowData[4] = usuarios.get(i).getCpf();
            rowData[5] = usuarios.get(i).getTelefone();
            rowData[6] = usuarios.get(i).getEmail();
            rowData[7] = usuarios.get(i).getRua();
            rowData[8] = usuarios.get(i).getNumero();
            rowData[9] = usuarios.get(i).getBairro();
            rowData[10] = usuarios.get(i).getCidade();
            rowData[11] = usuarios.get(i).getEstado();
         
            modelo.addRow(rowData);
        }
        
        jTable1_usuario.setModel(modelo);
        
    }//GEN-LAST:event_jButton_editarActionPerformed

    private void jTable1_usuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1_usuarioKeyReleased
       
         int linha = jTable1_usuario.getSelectedRow();
        String id = jTable1_usuario.getModel().getValueAt(linha, 0).toString();
        String nome = jTable1_usuario.getModel().getValueAt(linha, 1).toString();
        String login = jTable1_usuario.getModel().getValueAt(linha, 2).toString();
        String senha = jTable1_usuario.getModel().getValueAt(linha, 3).toString();
        String cpf = jTable1_usuario.getModel().getValueAt(linha, 4).toString();
        String telefone = jTable1_usuario.getModel().getValueAt(linha, 5).toString();
        String email = jTable1_usuario.getModel().getValueAt(linha, 6).toString();
        String rua = jTable1_usuario.getModel().getValueAt(linha, 7).toString();
        String numero = jTable1_usuario.getModel().getValueAt(linha, 8).toString();
        String bairro = jTable1_usuario.getModel().getValueAt(linha, 9).toString();
        String cidade = jTable1_usuario.getModel().getValueAt(linha, 10).toString();
        String estado = jTable1_usuario.getModel().getValueAt(linha, 11).toString();
        
        jTextField_nome.setText(nome);
        jTextField_login.setText(login);
        jPasswordField_senha.setText(senha);
        jTextField_cpf.setText(cpf);
        jTextField_telefone.setText(telefone);
        jTextField_email.setText(email);
        jTextField_rua.setText(rua);
        jTextField_numero.setText(numero);
        jTextField_bairro.setText(bairro);
        jTextField_cidade.setText(cidade);
        jTextField_estado.setText(estado);
        
        
        
    }//GEN-LAST:event_jTable1_usuarioKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLocalizar;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton jButton_editar;
    private javax.swing.JButton jButton_excluir;
    private javax.swing.JButton jButton_salvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField_senha;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1_usuario;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField_bairro;
    private javax.swing.JTextField jTextField_cidade;
    private javax.swing.JTextField jTextField_cpf;
    private javax.swing.JTextField jTextField_email;
    private javax.swing.JTextField jTextField_estado;
    private javax.swing.JTextField jTextField_login;
    private javax.swing.JTextField jTextField_nome;
    private javax.swing.JTextField jTextField_numero;
    private javax.swing.JTextField jTextField_rua;
    private javax.swing.JTextField jTextField_telefone;
    // End of variables declaration//GEN-END:variables
}
